### ISSUE TITLE
Multi-line chart

### ISSUE THREAD

**Issue by vnihoul77** [plamen-peshev/orgchartjs-templates#1]
Hello,
I am trying to implement a chart with the following layout:

https://imgur.com/a/DMwdTFP

The first nodes would be on two lines instead of one, and the children would hopefully expend above or ahead depending on their parent position.
Would this be doable? Any resource I could look at to achieve this?
Thanks

**Comment by ZornitsaPesheva** [comment]
Hi 
Is it a [Sequence diagram](https://mermaid-js.github.io/mermaid/#/sequenceDiagram?id=sequence-diagrams)?

**Comment by vnihoul77** [comment]
Not sure. I think what we're looking for is really a custom layout for the first nodes to be on two levels as it gets too busy when starting with +10.

Maybe this screenshot helps :
https://imgur.com/a/tkRbuic

**Comment by ZornitsaPesheva** [comment]
Unfortunately we don't support such layouts.

**Comment by vnihoul77** [comment]
Thanks
